writeHere/models.py
from datetime import datetime
from writeHere import db,login_manager
from flask_login import UserMixin


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


class User(db.Model,UserMixin):
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String(60),nullable=False)
    image_file = db.Column(db.String(20), nullable=False,default='default.jpg')
    post = db.relationship('Post', backref='author', lazy=True)

    def __repr__(self):
        return f"User('{self.username}','{self.email}','{self.image_file}')"

class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    content = db.Column(db.Text, nullable=False)
    date_posted = db.Column(db.DateTime,nullable=False,default=datetime.utcnow)
    user_id = db.Column(db.Integer,db.ForeignKey('user.id'),nullable=False)

    def __repr__(self):
        return f"Post('{self.title}','{self.date_posted}'"

writeHere/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import DataRequired,Length,Email,EqualTo, ValidationError
from flask_login import current_user


#ownclass
from writeHere.models import User



class RegistrationForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(),Length(min=2,max=20)])
    email = StringField('Email',validators=[DataRequired(),Email()])
    password = PasswordField('Password',validators=[DataRequired()])
    confirm_password = PasswordField('Confirm Password',validators=[DataRequired(),EqualTo('password')])
    submit = SubmitField('Sign Up')

    def validate_username(self,username):
        userFind = User.query.filter_by(username=username.data).first()

        if userFind:
            raise ValidationError("That username is taken. Please choose another one")

    def validate_email(self,email):
        emailFind = User.query.filter_by(email=email.data).first()

        if emailFind:
            raise ValidationError("That email is taken. Please choose another one")


class LoginForm(FlaskForm):
    email = StringField('Email',validators=[DataRequired(),Email()])
    password = PasswordField('Password',validators=[DataRequired()])
    remember = BooleanField('Remember Me')
    submit = SubmitField('Sign Up')

writeHere/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_mail import Mail
from writeHere.config import Config


db = SQLAlchemy()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.login_view = 'users.login'
login_manager.login_message_category = 'info'
# mail = Mail()


def create_app(config_class=Config):
    app = Flask(__name__)
    app.config.from_object(Config)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    # mail.init_app(app)

    from writeHere.main.routes import main
    from writeHere.users.routes import users

    app.register_blueprint(main)
    app.register_blueprint(users)

    return app

writeHere/main/routes.py
from flask import Blueprint, render_template


main = Blueprint('main',__name__,template_folder='C:\\Users\\HP TECHNOLOGY\\Write_Here\\writeHere\\templates')

@main.route('/')
@main.route('/home')
def home():
    return render_template('home.html',title='Home')

@main.route('/about')
def about():
    return render_template('about.html',title='About')

writeHere/users/routes.py
from flask import Blueprint, redirect, url_for, flash, render_template, request
from flask_login import current_user,login_user

#ownclass--
from writeHere.models import User, Post
from writeHere.users.forms import RegistrationForm, LoginForm
from writeHere import bcrypt, db

users = Blueprint('users',__name__)

@users.route("/register", methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    regForm = RegistrationForm()
    if regForm.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(regForm.password.data).decode('utf-8')
        userObj = User(username=regForm.username.data, email=regForm.email.data, password=hashed_password)
        db.session(userObj)
        db.session.commit()
        flash('Your account has been created!, You are now able to login','success')
        return redirect(url_for('main.home'))
    return render_template('register.html',title='Register',form=regForm)


@users.route("/login", methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    regForm = LoginForm()
    if regForm.validate_on_submit():
        userFind = User.query.filter_by(email=regForm.email.data).first()
        if userFind and bcrypt.check_password_hash(userFind.password, regForm.password.data):
            login_user(userFind,remember=regForm.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash("Login unsuccessful. Please check your email and password ",'danger')

    return render_template('login.html',form=regForm,title='Login')

writeHere/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content%}

writeHere/templates/home.html
{% extends "layout.html" %}
{% block content %}
    <h1>home Page</h1>
{% endblock content%}

writeHere/templates/layout.html
<!doctype html>
<html lang="en" class="sm:scroll-smooth">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Acme Rockets</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static',filename='css/style.css') }}">
</head>
<body class="min-h-screen bg-slate-50 dark:bg-black dark:text-white">
    <header class="bg-teal-700 text-white sticky top-0 z-10">
        <section class="max-w-4xl mx-auto p-4 flex justify-between items-center">
            <h1 class="text-3xl font-medium">
                <a href="#"> 🚀 Write Here </a>
            </h1>
            <div>
                <nav class="hidden sm:block space-x-8 text-xl" aria-label="main">
                    {% if current_user.is_authenticated: %}
                        <a href="#" class="hover:opacity-90">New Post</a>
                        <a href="#" class="hover:opacity-90">Account</a>
                        <a href="#" class="hover:opacity-90">Logout</a>
                    {% else: %}
                        <a href="{{ url_for('users.login') }}" class="hover:opacity-90">Login</a>
                        <a href="{{ url_for('users.register') }}" class="hover:opacity-90">Signup</a>
                    {% endif%}
                </nav>
            </div>
        </section>
    </header>

    <main class="max-w-4xl mx-auto">
        <section id="hero" class="flex flex-col-reverse justify-center sm:flex-row p-6 items-center gap-8 mb-12 scroll-pt-60">
            <article class="sm:w-2/3">
                   {% with messages = get_flashed_messages(with_categories=true) %}
                        {% if messages %}
                            {% for category, message in messages %}
                                <div class="">
                                    {{ message }}
                                </div>
                            {% endfor %}
                        {% endif %}
                    {% endwith %}
                {% block content %}{% endblock %}
            </article>
            <article class="sm:w-1/3">

            </article>
        </section>


    </main>

</body>
</html>

writeHere/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <section id="contact" class="p-6 my-12 scroll-mt-16 widescreen:section-min-height tallscreen:section-min-height">
            <h2 class="text-4xl font-bold text-center sm:text-5xl mb-6 text-slate-900 dark:text-white">
                Login
            </h2>
            <form action="" method="post" class="max-w-4xl mx-auto text-2xl sm:text-3xl flex flex-col items-lefr gap-4">

                <div class="form-group">
                    {{ form.email.label(class="form-control-label", for="email") }}

                    {% if form.email.errors %}
                        {{ form.email(class="") }}
                        <div class="text-red-600">
                          {% for error in form.email.errors %}
                            <span> {{ error }}</span>
                          {% endfor %}
                        </div>
                    {% else %}
                      {{ form.email(class="w-full text-black text-2xl sm:text-3xl p-3 rounded-xl border border-solid border-slate-900 dark:border-none") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label", for="password") }}

                    {% if form.password.errors %}
                        {{ form.password(class="") }}
                        <div class="text-red-600">
                          {% for error in form.password.errors %}
                            <span> {{ error }}</span>
                          {% endfor %}
                        </div>
                    {% else %}
                      {{ form.password(class="w-full text-black text-2xl sm:text-3xl p-3 rounded-xl border border-solid border-slate-900 dark:border-none") }}
                    {% endif %}
                </div>

                 <div>
                     <span>{{ form.remember(class="h-4 w-4 text-indigo-600 focus:ring-indigo-500 border-gray-300 rounded")}}</span>
                    <span>{{ form.remember.label(class="ml-2 block text-sm text-gray-900")}}</span>
                </div>
                <div class="form-group">
                    {{ form.submit(class="bg-teal-700 hover:bg-teal-600 active:bg-teal-500 text-white p-3 w-48 rounded-xl border border-solid border-slate-900 dark:border-none") }}
                </div>
                
            </form>
        </section>
{% endblock content%}

writeHere/templates/register.html
{% extends "layout.html" %}
{% block content %}
    <section id="contact" class="p-6 my-12 scroll-mt-16 widescreen:section-min-height tallscreen:section-min-height">
            <h2 class="text-4xl font-bold text-center sm:text-5xl mb-6 text-slate-900 dark:text-white">
                Register
            </h2>
            <form action="" method="post" class="max-w-4xl mx-auto text-2xl sm:text-3xl flex flex-col items-lefr gap-4">

                <div class="form-group">
                    {{ form.username.label(class="form-control-label", for="username") }}

                    {% if form.username.errors %}
                        {{ form.username(class="") }}
                        <div class="text-red-600">
                          {% for error in form.username.errors %}
                            <span> {{ error }}</span>
                          {% endfor %}
                        </div>
                    {% else %}
                      {{ form.username(class="w-full text-black text-2xl sm:text-3xl p-3 rounded-xl border border-solid border-slate-900 dark:border-none") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label", for="email") }}

                    {% if form.email.errors %}
                        {{ form.email(class="") }}
                        <div class="text-red-600">
                          {% for error in form.email.errors %}
                            <span> {{ error }}</span>
                          {% endfor %}
                        </div>
                    {% else %}
                      {{ form.email(class="w-full text-black text-2xl sm:text-3xl p-3 rounded-xl border border-solid border-slate-900 dark:border-none") }}
                    {% endif %}
                </div>

                <div class="form-group">
                    {{ form.password.label(class="form-control-label", for="password") }}

                    {% if form.password.errors %}
                        {{ form.password(class="") }}
                        <div class="text-red-600">
                          {% for error in form.password.errors %}
                            <span> {{ error }}</span>
                          {% endfor %}
                        </div>
                    {% else %}
                      {{ form.password(class="w-full text-black text-2xl sm:text-3xl p-3 rounded-xl border border-solid border-slate-900 dark:border-none") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.confirm_password.label(class="form-control-label", for="confirm_password") }}

                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="") }}
                        <div class="text-red-600">
                          {% for error in form.confirm_password.errors %}
                            <span> {{ error }}</span>
                          {% endfor %}
                        </div>
                    {% else %}
                      {{ form.confirm_password(class="w-full text-black text-2xl sm:text-3xl p-3 rounded-xl border border-solid border-slate-900 dark:border-none") }}
                    {% endif %}
                </div>


                <div class="form-group">
                    {{ form.submit(class="bg-teal-700 hover:bg-teal-600 active:bg-teal-500 text-white p-3 w-48 rounded-xl border border-solid border-slate-900 dark:border-none") }}
                </div>

            </form>
        </section>
{% endblock content%}